apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-auditor
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-auditor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-auditor
    spec:
      containers:
      - env:
        - name: cluster_name
          value: foo
        - name: es_host
          value: elasticsearch-master
        - name: es_port
          value: "9200"
        - name: es_protocol
          value: http
        - name: es_index_pods
          value: k8s-pods
        - name: es_index_configmaps
          value: k8s-configmaps
        - name: LOG4J_CONFIGURATION_FILE
          value: lib/log4j2.xml
        - name: reindex_events
          value: "false"
        image: AWS_ACCOUNT_NUMBER.dkr.ecr.eu-west-1.amazonaws.com/environment-mgmt/k8s-auditor:3.0.1
        imagePullPolicy: IfNotPresent
        name: k8s-auditor
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-auditor
      serviceAccountName: k8s-auditor
      terminationGracePeriodSeconds: 30
