{{- if contains "int" .Values.cluster_name }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki-aws-fmlabs-xyz/sign/aws-fmlabs-xyz
    server: https://vault.your.domain:8200
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVmRENDQTJTZ0F3SUJBZ0lCQVRBTkJna3Fo
      a2lHOXcwQkFRc0ZBRENCdURFTE1Ba0dBMVVFQmhNQ1IwSXgKRHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNU2d3SmdZRFZRUUtEQjlHYjI5MApjSEpwYm5RZ1RXVmth
      V0VnU1ZRZ1UyVnlkbWxqWlhNZ1RIUmtNU1l3SkFZSktvWklodmNOQVFrQkZoZHBibVp2ClFHWnZi
      M1J3Y21sdWRHMWxaR2xoTG01bGRERTFNRE1HQTFVRUF3d3NSbTl2ZEhCeWFXNTBJRTFsWkdsaElG
      SnYKYjNRZ1EyVnlkR2xtYVdOaGRHbHZiaUJCZFhSb2IzSnBkSGt3SGhjTk1qRXdOVEUyTWpFeE1E
      SXpXaGNOTWpJdwpOVEUyTWpFeE1ESXpXakNCdkRFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHCkExVUVCd3dHVEc5dVpHOXVNU2d3SmdZRFZRUUtEQjlHYjI5MGNI
      SnBiblFnVFdWa2FXRWdTVlFnVTJWeWRtbGoKWlhNZ1RIUmtNU1l3SkFZSktvWklodmNOQVFrQkZo
      ZHBibVp2UUdadmIzUndjbWx1ZEcxbFpHbGhMbTVsZERFNQpNRGNHQTFVRUF3d3dSbTl2ZEhCeWFX
      NTBJRTFsWkdsaElFeGhZbk1nUTJWeWRHbG1hV05oZEdsdmJpQkJkWFJvCmIzSnBkSGtnTFNCSU1J
      SUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd3RQejh0bWYKMHF5NDdv
      dWVJbmU0UTVidkNVRS8yamtmUkpFQ3dVOWNWZ2RWTWkxa2V6KzBVWGJla2VTQ2dLczdiN01jdUJW
      SApqaVFWSkxtQVhzVUVrVFdlMEJCajIrdkVJU25kUm9WTXpyUDM5b2VrTzV4VzV0WldiUS8vOVRV
      c0t0N05uNXZwCkVIMVpMT0RONWcvV09IbTIrOFM1Y2g2eW9aejVHVzYxcER0VThBdG9yWTdFVHNK
      VFcwRUZMNWQvaThZZHkySHIKdC9RcjMwWTNLT0ZYb0xvN2FxYS92bHFVVlg4ZUJ0dzNnVXFxMXkw
      WkxzUmFENWIwSDV4aitpanZyNm9SYmFsWgpqR3dsWXlQMVhkTXpsMmdIeGpuNnd1M1pMc0RMbjlP
      ZHRucmV0cGhKQWplWm9RYTdkaVZYdHZ5VnJzZ21TdDJyCnJ6cHBCVFI2OEtmWWJRSURBUUFCbzRH
      S01JR0hNRGNHQ1dDR1NBR0crRUlCRFFRcUZpaFBVRTV6Wlc1elpTQkgKWlc1bGNtRjBaV1FnUTJW
      eWRHbG1hV05oZEdVZ1FYVjBhRzl5YVhSNU1CMEdBMVVkRGdRV0JCUjFJL0JLc3dmcQprdUZ4czlX
      M0F4dGM5ZTJ0NGpBZkJnTlZIU01FR0RBV2dCUUJOYVB4YURyK3RmK2wrMFdBYjJzdHNxUzlGVEFN
      CkJnTlZIUk1FQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF3UzQrelZrNXpnR3pN
      RkdBcWNReEEKenZ4aVZsSHdKa3RHSkFYUThFUEdrKzQyN0dsS0xYWmkzbTV3V0VIVmhWN1lNemVS
      b3FBRE03L2VKUjhKT1hLNgo0UE9GWVBsQ0g3RDFadkZ1NVowcklEbStHQldybkNhc0ptR3M5cjBY
      SUlrNnhsaG5mWDF3bFdLOXpWdU1rcVMzCktGUU1jd0VWUTY5YTZMZEJKQVUyeFN6UC94YU5GcnM5
      WXQzWVV0YU9nOTJUd2dsek1oUFBSZG9HS0syYXBYTGwKbUVKeUR6NEZHVDhpcWZMRUZCODMzNHNn
      Mmc1MzA3MlE4aVVYZWZqV2FQdDNsQWU5SnNGei9XbjR1WG5qU3pNMApVYUs0TytnUExscUxCbWtK
      RFU3b1U1MHd0dUVHLytaTEpkWXNGWGtzYnZyQ2Z3SERvQlJsYVF6TGo2MEkvYS9GCi0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVlRENDQTJD
      Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBRENCdURFTE1Ba0dBMVVFQmhNQ1IwSXgKRHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNU2d3SmdZRFZRUUtEQjlH
      YjI5MApjSEpwYm5RZ1RXVmthV0VnU1ZRZ1UyVnlkbWxqWlhNZ1RIUmtNU1l3SkFZSktvWklodmNO
      QVFrQkZoZHBibVp2ClFHWnZiM1J3Y21sdWRHMWxaR2xoTG01bGRERTFNRE1HQTFVRUF3d3NSbTl2
      ZEhCeWFXNTBJRTFsWkdsaElGSnYKYjNRZ1EyVnlkR2xtYVdOaGRHbHZiaUJCZFhSb2IzSnBkSGt3
      SGhjTk1qRXdOVEUyTWpBMU9ERTVXaGNOTXpFdwpOVEUwTWpBMU9ERTVXakNCdURFTE1Ba0dBMVVF
      QmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHCkExVUVCd3dHVEc5dVpHOXVNU2d3
      SmdZRFZRUUtEQjlHYjI5MGNISnBiblFnVFdWa2FXRWdTVlFnVTJWeWRtbGoKWlhNZ1RIUmtNU1l3
      SkFZSktvWklodmNOQVFrQkZoZHBibVp2UUdadmIzUndjbWx1ZEcxbFpHbGhMbTVsZERFMQpNRE1H
      QTFVRUF3d3NSbTl2ZEhCeWFXNTBJRTFsWkdsaElGSnZiM1FnUTJWeWRHbG1hV05oZEdsdmJpQkJk
      WFJvCmIzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2pY
      REg1L2JEVDd6SFoKYzd4cDh4SVBFcWxMQTVNZTgwSGZyUHF2RFlhZzRhdHRkbm1NcGpBbkVPTVlq
      dFEwR29FQWpvdnptbmtyZGdVKwovU0R2amc1SXJ4a3pnK0RxaEw3eHRmT3JUOW5wbnVOU1lidWF2
      SXJqcENyMEQ4MlBCRzRiVG5IWXBuYVA5NWdtCnF1WHJIdGVCdHFHUEdKTTFuNGNOVkhvR0ZFbGlh
      SnhsVXhhZG44RDgwYUNUTUMwZEpEWlZueURTWWg4bmUvZFMKRjZueHFCOHdwbzFBeGdpQWV5cVBh
      eGdha05lWTY4STZWdk54cEhNL0NjWGF2czJNdlgyeTBSWUJaYTN5UmtRcgp1Nyt3R1RZZnJCZ0ND
      endxVk9iNXJQL3E1OFByNjNKNWE4aTZYK0FKWlNnZENUeUx5RnVwTGozS2VzOURXallmCm83RTNP
      ZVVaQWdNQkFBR2pnWW93Z1ljd053WUpZSVpJQVliNFFnRU5CQ29XS0U5UVRuTmxibk5sSUVkbGJt
      VnkKWVhSbFpDQkRaWEowYVdacFkyRjBaU0JCZFhSb2IzSnBkSGt3SFFZRFZSME9CQllFRkFFMW8v
      Rm9PdjYxLzZYNwpSWUJ2YXkyeXBMMFZNQjhHQTFVZEl3UVlNQmFBRkFFMW8vRm9PdjYxLzZYN1JZ
      QnZheTJ5cEwwVk1Bd0dBMVVkCkV3UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFD
      c2JSSzE4a29WSnRqQ1dabElOekUvZVY4aXkKUzNaQzNFa1ZFc04zZzdTbGtuOXlrNlFJTU9WelVt
      dTZtRk5jTU1vOGM3cXpEandlOXNwREtabElPT1ZwSyt6ZgorVUVPSklGU25pTE5mVEhod2lsK1Zo
      RytyUGpSbk84d0g4VmZ3U2tlMm1ISU90VzZHU1dhQzR0eVBzUXNLc0FJClFMUE9Cb3I1R3BZcG1w
      VU5oZ3h4ZmYxU2ZpVDFXVmtHaG1nN2xGNzV2Zjl3SWlDdmVBRkdkTVZXeTdHQjlSUm0KMnh4bFhM
      V2NEVGV5WUl1SlZHcjVjTzRwQVJkSUFURXVvbjJ4Rm1kdjBBTVR5NThtckV3YW5JTXZOMmE4NHJ1
      WApIejVyN3ZJOC9WVWxhNnRQN3Q0NE45cEtqVC83MWtTRG5qbWRuZ0JiUGdNZ2JXdzZNUEpCa1M0
      T291Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    auth:
      appRole:
        path: approle
        roleId: 66b38cc8-c992-966d-bcb3-c3a8e4e77e01
        secretRef:
          name: cert-manager-vault-approle
          key: secretId
{{- end }}
