{{- if contains "int" .Values.cluster_name }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki-aws-your-domain/sign/aws-your-domain
    server: https://vault.your.domain:8200
    caBundle: ""
    auth:
      appRole:
        path: approle
        roleId: 66b38cc8-c992-966d-bcb3-c3a8e4e77e01
        secretRef:
          name: cert-manager-vault-approle
          key: secretId
{{- end }}
