awsRegion: ${region}
autoDiscovery:
  clusterName: ${cluster_name}
rbac:
  serviceAccount:
    annotations: {}
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  # write-status-configmap: true
  # status-config-map-name: cluster-autoscaler-status
  # leader-elect: true
  # skip-nodes-with-local-storage: true
  expander: least-waste
  # scale-down-enabled: true
  # balance-similar-node-groups: true
  # min-replica-count: 0
  # scale-down-utilization-threshold: 0.5
  # scale-down-non-empty-candidates-count: 30
  # max-node-provision-time: 15m0s
  # scan-interval: 10s
  # scale-down-delay-after-add: 10m
  # scale-down-delay-after-delete: 0s
  # scale-down-delay-after-failure: 3m
  scale-down-unneeded-time: 5m
  # skip-nodes-with-system-pods: true
fullnameOverride: "cluster-autoscaler"
priorityClassName: "system-cluster-critical"

image:
%{ if custom_docker_registry != "" }
  repository: ${custom_docker_registry}/autoscaling/cluster-autoscaler
%{ else }
  repository: autoscaling/cluster-autoscaler
%{ endif }
  tag: v1.20.0
