kyverno:
  image:
  %{ if custom_docker_registry != "" }
    repository: ${custom_docker_registry}/kyverno/kyverno
  %{ endif }
    tag: v1.3.6

  metricsService:
    create: true
    type: ClusterIP
    ## Kyverno's metrics server will be exposed at this port
    port: 8000
    ## The Node's port which will allow access Kyverno's metrics at the host level. Only used if service.type is NodePort.
    nodePort:
    ## Provide any additional annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '8000'
