---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-auditor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-auditor
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - ingresses
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-auditor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-auditor
subjects:
- kind: ServiceAccount
  name: k8s-auditor
  namespace: monitoring
