apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-lb
  annotations:
    policies.kyverno.io/title: Disallow LoadBalancer
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      Allow service type LoadBalancer only for istio
spec:
  validationFailureAction: enforce
  rules:
  - name: validate-nodeport
    
    match:
      resources:
        kinds:
        - Service
    
    exclude:
      resources:
        namespaces:
        - istio-system
        name: "istio-*"

    validate:
      message: "Services of type LoadBalancer are not allowed."
      pattern: 
        spec:
          type: "!LoadBalancer"
